#!/usr/bin/env bash
# Fetch app secrets from GCP Secret Manager and materialize them into
# `.env.secrets`, which docker-compose reads via `env_file:`.
#
# Run this before `docker compose up -d` whenever a secret rotates.
# Requires `gcloud auth login` as someone with secretAccessor on the
# three secrets in the cdsci-infra project.
#
# This script is intentionally simple — no flags, no dry-run, no diffing.
# If you need to rotate a secret, bump the version in SM, re-run, recycle
# the container. The container reads env at startup only.

set -euo pipefail

PROJECT=cdsci-infra
OUT="$(dirname "$0")/.env.secrets"

get() {
    gcloud secrets versions access latest --secret="$1" --project="$PROJECT"
}

# Build the file in a tempfile then atomic-rename so a partial run never
# leaves a half-written .env.secrets in place.
tmp="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
    echo "# Generated by deploy/onclappc02/fetch-secrets.sh — do not edit by hand."
    echo "# Source of truth is GCP Secret Manager in project $PROJECT."
    echo "OAUTH_CLIENT_ID=$(get cancerdatasci-oauth-client-id)"
    echo "OAUTH_CLIENT_SECRET=$(get cancerdatasci-oauth-client-secret)"
    echo "SESSION_SECRET=$(get cmgd-api-session-secret)"
    echo "OPERATOR_TOKEN=$(get cmgd-api-operator-token)"
} > "$tmp"

chmod 600 "$tmp"
mv "$tmp"   "$OUT"
trap - EXIT

echo "Wrote $OUT (mode 600). Recycle the API container to pick up changes:"
echo "  docker compose -f $(dirname "$0")/docker-compose.yml up -d nf_telemetry_api"
